### ISSUE TITLE
Setup CD system with chocolate release bin

### ISSUE THREAD

**Issue by islami00** [chocolatenetwork/chocolate-parachain#12]
### Context

As of now, the frontend ships two release channels: `nightly` and a production release for the demo. Since the frontend gets updates more frequently, the releases have used the same temporary chain deployed to gcp. This chain in turn uses a docker image built from dev/master as the case may be when deploying.

The problem becomes updating the docker image as the Dockerfile builds the chain from scratch, or in the case where we need two copies of the chain while working on new changes in dev. Hence, we should adopt a CD system similar to the frontend with `nightly` for dev releases , and a production release to match.

This release would also provide binaries that can be easily downloaded to the respective image and used directly.

### Todos

- [ ] Release github action compatible with `nightly` and `production` builds
- [ ] Include built binary in each release
- [ ] Use the binaries for deploying to gcp.
