### ISSUE TITLE
Cleanup tests in chocolate and Users pallet

### ISSUE THREAD

**Issue by islami00** [chocolatenetwork/chocolate-parachain#18]
### Context

During the migration, tests for chocolate and users pallet were not updated, so they are now failing.

### Todos:

- [ ] Update test runtime for chocolate pallet
- [ ] Update test runtime for users pallet
- [ ] Update tests for chocolate pallet
