### ISSUE TITLE
Migrate Chocolate node repository to Parachain Repository

### ISSUE THREAD

**Issue by islami00** [chocolatenetwork/chocolate-parachain#5]
### Context

As we complete our deliverables, I hope we're able to gradually migrate our substrate codebase to this repository

### Aim:

1. To migrate all pallets used in [chocolatenetwork/chocolate-node](https://github.com/chocolatenetwork/chocolate-node) to this repository. 
2. Migrate all token/node namings

### Todos: 

**Pallet migration**

- [x] Adapt and move chocolate pallet 
- [x] Adapt and move Users pallet
- [x] Add Treasury pallet

**Naming and licensing**

- [ ] Rename bin in codebase to chocolate-collator
- [x] Update README to match chocolate-node codebase
- [ ] Add license info to pallets

**Comment by islami00** [comment]
> @islami00 Is this already completed?

Not quite, still need to rename things. The progress so far is merged into https://github.com/chocolatenetwork/chocolate-parachain/tree/multiassets-pallet
