### ISSUE TITLE
Use `with_transaction_result` from orml-utilities

### ISSUE THREAD

**Issue by islami00** [chocolatenetwork/chocolate-parachain#9]
The orml-utilities crate provides us with `with_transaction_result` for automatically rolling back changes for extrinsics that have multiple steps that may fail after making storage writes. this is more graceful than manually rolling state back.

## Todos

- [ ]  Refactor extrinsics of chocolate pallet to use `with_transaction_result` 
- [ ] simplify utility functions that rollback, e.g `reward` of `ProjectIO` 
- [ ] Simplify utility functions that assume all works out e.g `reward_user` (implemented on pallet)
